name: Test

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # ref: https://github.com/pre-commit/action
      # Run "pre-commit run --all-files"
      - uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: |
          pip install -r aws-sam-msteams-costbot/requirements-dev.txt

      - run: |
          cd aws-sam-msteams-costbot
          python -mpytest -v tests/
